included: # paths to ignore during linting. Takes precedence over `included`.
  - BaseFramework 
  - IITC-Mobile 
  - ViewInIITC

disabled_rules:
  - line_length
  - identifier_name
  - closure_parameter_position

force_cast: warning
force_try: warning

